### ISSUE TITLE
Pausing and then playing skips to next track

### ISSUE THREAD

**Issue by Andskiman** [devoctomy/doesnotwant#1]
When I'm in playlist radio and pausing, and then resume playing it skips the current track and goes to the next.
Version: 1.0.5769.21757

**Comment by NickDevoctomy** [comment]
Thanks for reporting the issue, I can confirm this is happening. I shall get a fix in as soon as I can and update you.

**Comment by Andskiman** [comment]
Cheers man! Thanks a billion for the effort.
Another thing that is semi-related to this issue:
If you press the "next track" button, and it lands on a track that has been filtered, it still plays it. And it won't show up as "currently playing" in DNW, the previous track will. However pressing pause-play makes it skip the filtered track and on to one that hasn't been added to the filter. 
So in other words; the pause/play issue cancels out another issue.

UPDATE: Seems to skip next track properly if they've been filtered under the artist name. Problem seems to occur if the track itself has been filtered.

**Comment by NickDevoctomy** [comment]
I've fixed the initial track skip which will be in the next build, I won't be able to look into the other issue until tonight, but will try to upload a new installer when I do. Hopefully I'll have the other issue fixed too if I can replicate it, the API for tracking local playback isn't an official one and seems to suffer from some lag which night be causing this.

**Comment by NickDevoctomy** [comment]
I couldn't replicate the second issue you mentioned but the first one is fixed.  I've been testing with a playlist that contains about 10 tracks, 2 are blocked, one by artist name and the other by track URI, they both skip as expected, either when letting the previous track finish, or pressing "Next" manually.

It could be some kind of delay in the local API.

If you continue to have issues let me know and I'll put some kind of polling in so it will pick it up eventually.

**Comment by NickDevoctomy** [comment]
You can download it from here now

[DoestNotWant - Release History](http://devoctomy.s3.amazonaws.com/installers/DoesNotWant/History.html)

**Comment by Andskiman** [comment]
Thanks, man!
As for the other problem I described; it's happened once without me pressing next track, so it's not necessarily uniquely linked to doing that. Probably just lag as you've mentioned.

It's so nice to finally be able to use the radio in order to discover new artists/tracks, without having to get the same 15 tracks in an infinite loop.

**Comment by NickDevoctomy** [comment]
On that note, a common complaint from people is that Spotify repeats itself too much, I could add something to help stop that too maybe lol.  Cheers, I shall close the issue.
